image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build
    
    cd build

    curl -s https://report.ci/annotate.py > annotate.py
    
    pip install --user conan

    set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Scripts

    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 

    cmake c:\projects\source -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE:STRING=Release

    cmake --build . --config "Release" | python annotate.py --name "MSVC Build" --tool msvc --tee
test_script:
- cmd: ctest -C Release

on_finish:
  - curl -s https://report.ci/upload.py | python